import './globals.css'

export const metadata = {
  title: 'Flexi App',
  description: 'Generated by Create Next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        {children}
      </body>
    </html>
  )
}
